language: node_js
node_js:
  - "16.3.0"
install:
    - npm install
script:
    - npm run test
    - npm run build
deploy:
  provider: heroku
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  repo: Daniel54088/nine-web-service
  target_branch: main 
    