export const CHECK_WORKS = 'CHECK_WORKS';

export const FETCH_POST_FROM_URL = "FETCH_POST_FROM_URL";
export const FETCH_POST_FROM_URL_SUCCESS = "FETCH_POST_FROM_URL_SUCCESS";
export const FETCH_POST_FROM_URL_FAIL = "FETCH_POST_FROM_URL_FAIL"
