# CircleCI
version: 2.1

jobs:
  build-and-test:
    steps:

      - checkout
      
      - run:
          command: |
           npm install
          name: Install

      - run:
          command: |
           npm test
          name: Test


workflows:
  main:
    jobs:
      - build-and-test